// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC1o7-hAjQPo8ASqrEvzmj_s-aGsLQato',
    appId: '1:197806628424:web:ee585705cebac4c200027d',
    messagingSenderId: '197806628424',
    projectId: 'flutter-projects-1f795',
    authDomain: 'flutter-projects-1f795.firebaseapp.com',
    storageBucket: 'flutter-projects-1f795.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrQrdfYNm727Zb_VXMpfKmeFm7XScBgM8',
    appId: '1:197806628424:android:0d6db885bc9716ae00027d',
    messagingSenderId: '197806628424',
    projectId: 'flutter-projects-1f795',
    storageBucket: 'flutter-projects-1f795.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAghzgzjuDZ38mXc5tGr0Q1_Zq03yNXLcs',
    appId: '1:197806628424:ios:dc6b63256356027f00027d',
    messagingSenderId: '197806628424',
    projectId: 'flutter-projects-1f795',
    storageBucket: 'flutter-projects-1f795.firebasestorage.app',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAghzgzjuDZ38mXc5tGr0Q1_Zq03yNXLcs',
    appId: '1:197806628424:ios:dc6b63256356027f00027d',
    messagingSenderId: '197806628424',
    projectId: 'flutter-projects-1f795',
    storageBucket: 'flutter-projects-1f795.firebasestorage.app',
    iosBundleId: 'com.example.notifications',
  );
}
